application: udacity-homework4-problemset3
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /blog/(\d+)
  script: udacity-homework4-problemset3.app

- url: /.*
  script: udacity-homework4-problemset3.app

libraries:
- name: jinja2                                                                  
  version: latest   

builtins:
- remote_api: on
